metric_list:
  - _target_: torchmetrics.Accuracy
    threshold: 0.5
  - _target_: torchmetrics.Precision
  - _target_: torchmetrics.AUROC
  - _target_: torchmetrics.ConfusionMatrix
    num_classes: 2
