metric_list:
  - _target_: torchmetrics.Accuracy
  - _target_: torchmetrics.Precision
  - _target_: torchmetrics.Recall
  - _target_: torchmetrics.AUROC
    num_classes: 2
  # - _target_: torchmetrics.ConfusionMatrix
  #   num_classes: 2
